### ISSUE TITLE
Menu Bar doesn't work in mobile view, on desktop

### ISSUE THREAD

**Issue by kevintpeng** [WGDEVS/WGDEVS.github.io#2]
pls fix, cannot see your other side projects. @Manas-Joshi-UW @ryannewman2828 help?

![image](https://cloud.githubusercontent.com/assets/7998752/23346511/a738c44a-fc4f-11e6-97a3-690a335d07a2.png)

**Comment by Manas-Joshi-UW** [comment]
this isnt fixed!

**Comment by WGDEVS** [comment]
@Manas-Joshi-UW Did you try clearing your cache?
